### ISSUE TITLE
Support for RTL (Under Development)

### ISSUE THREAD

**Issue by iliyass-zamouri** [iliyass-zamouri/flutter_agenda#1]
The support for RTL is Under Development and will be available soon.

**Comment by CripyIce** [comment]
Looking forward for RTL support!

**Comment by iliyass-zamouri** [comment]
I have some performance issue with this package, I'm preparing another one with only bidirectionalScroll (this one is using diagonalScroll behavior). I might override this one with it.

**Comment by iliyass-zamouri** [comment]
> Looking forward for RTL support!

I have updated the package scroll to bidirectional scroll it's under the 3.0.0 version, check it out if you want.

**Comment by CripyIce** [comment]
@iliyass-zamouri Thanks for your effort!
But, there are some bugs so I'll open a new issue.
